version: '3.8'

services:
  acapy:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.9.0
    container_name: acapy
    ports:
      - "11000:11000"
      - "8000:8000"
    command: start --label idenlight --tails-server-base-url http://demo.id-ideal.de/tails/ --webhook-url http://demo.id-ideal.de/ws/webhooks -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://test.bcovrin.vonx.io/genesis --seed HTWDresden0000000000000000000001 --endpoint http://demo.id-ideal.de/acapyse/ --debug-connections --auto-provision --wallet-type askar --wallet-name idenlight --wallet-key secret --auto-accept-invites --auto-accept-requests --log-level info

    networks:
      - web

  webhook:
    build: ./webhook_service
    container_name: webhook
    ports:
      - "5001:5001"
    networks:
      - web

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - web

  traefik:
    image: traefik:v2.6
    command:
      # Experimentell, um das Dashboard ohne Zugriffsschutz aufzurufen
      #- "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=true"
      - "--providers.docker.network=web"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

networks:
  web:
    driver: bridge
